<a href="https://colab.research.google.com/github/ycui4407/cs250-fall2026-Yi-Cui/blob/main/Labs/L01_cui_yi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 1: Your First Python Program in Google Colab

CS 250 — Introduction to Programming


## Lab information

| | |
|---|---|
| **Course** | CS 250 — Introduction to Programming |
| **Term** | Fall 2026, Section A |
| **Institution** | San Francisco Bay University |
| **Lab duration** | 50 minutes |
| **Language** | Python 3 |
| **Environment** | Google Colab |

### Your information

Double-click this cell to edit it, fill in the four fields, then press **Shift + Enter** to save it.

- **Student name:**yi_cui
- **Date:**08/20/2026
- **Lab section:**lab01


## Learning objectives

By the end of this lab you should be able to:

1. Open and navigate a Google Colab notebook.
2. Tell the difference between a Markdown cell and a code cell.
3. Run Python code and find its output.
4. Use `print()` to display text and simple values.
5. Add useful comments to a Python program.
6. Modify a Python program and run it again.
7. Predict the output of simple `print()` statements.
8. Identify and correct simple syntax, runtime, and logic errors.
9. Write a small Python program that produces formatted output.


## Before you begin

📘 **Read**

Everything you need is already in this notebook. You do **not** need to install anything,
upload any files, or connect to Google Drive.

**Two things to do first:**

1. **Make your own copy.** Go to **File → Save a copy in Drive**. Work in that copy —
   otherwise your changes may not be saved.
2. **Expect a message from Colab.** When you run your first cell, Colab may spend a few
   seconds connecting, or show a notice saying the notebook was not authored by Google.
   Both are normal. Choose **Run anyway** if you are asked.

**A few words you will see today:**

- **Cell** — one block in the notebook. This block is a cell.
- **Markdown cell** — a cell that holds text: instructions, questions, your written answers.
- **Code cell** — a cell that holds Python code you can run. It has a ▶ Run button on its left.
- **Output** — what a program displays. It appears directly below the code cell that produced it.
- **Error** — Python telling you it could not do something. Errors are normal and useful, not a
  sign that you did something wrong.

**Cell labels used in this lab:**

| Label | What it means |
|---|---|
| 📘 Read | Information to read. Nothing to do. |
| ▶️ Try It | Run the cell exactly as it is. |
| ✏️ Your Task | Write or change code yourself. |
| 🤔 Prediction | Write what you think will happen, **before** running. |
| 🐞 Debug | Find and fix a problem in the code. |
| ✅ Check Your Work | A short checklist. |
| 💭 Reflection | Write a short answer in your own words. |


## Part 1: Getting Started with Google Colab

⏱ **Target time: 5 minutes**


📘 **Read**

This notebook is made of two kinds of cells:

- **Markdown cells**, like this one, hold instructions and explanations. They do not run.
- **Code cells** hold Python code. Each one has a ▶ **Run** button on its left side.

**How to run a code cell:**

1. Click anywhere inside the code cell.
2. Click the ▶ **Run** button on its left, or press **Shift + Enter**.
3. Look **below** the cell — that is where the output appears.

You can change the code in a cell and run it again as many times as you like. The output
below it is replaced each time.


▶️ **Try It** — Run the cell below and check that a line of text appears underneath it.


In [1]:
# Part 1 - Try It
# Click the Run button on the left of this cell, or press Shift + Enter.

print("Google Colab is ready!")


Google Colab is ready!


✏️ **Your Task**

1. Click inside the code cell below.
2. Change the text between the quotation marks to a greeting of your own.
3. Run the cell again and confirm that your new text appears.


In [2]:
# Part 1 - Your Task
# TODO: Change the message below to a greeting of your own, then run this cell again.

print("welcome to CS 250L")


welcome to CS 250L


✅ **Check Your Work**

Edit this cell and put an `x` between the brackets for each item you have done.

- [ ] I found the Run button.
- [ ] I ran a code cell.
- [ ] I found the output.
- [ ] I know how to edit a cell and run it again.


## Part 2: Run Your First Python Program

⏱ **Target time: 7 minutes**


📘 **Read**

Here is the program from Lecture 1. It has three lines:

- Line 1 starts with `#`. That makes it a **comment** — a note for people. Python skips it.
- Lines 2 and 3 each use `print()` to display a message.

Read the program in the next cell, but **do not run it yet**.


In [3]:
# My first Python program
print("Welcome to CS 250!")
print("Python is fun!")


Welcome to CS 250!
Python is fun!


🤔 **Prediction**

Before running the cell above, answer these two questions in this cell.
Double-click here to edit it.

1. How many lines of output will appear?
2. Exactly what will each line say?

*Type your answer here:*
1. 2 lines
2.Welcome to CS 250!
Python is fun!


✏️ **Your Task**

1. Run the cell above and compare the output with your prediction.
2. In the cell below, change the second message to something of your own.
3. Add a **third** `print()` statement.
4. Run the cell below and read the output carefully.


In [4]:
# TODO 1: Change the second message.
# TODO 2: Add a third print statement.

print("Welcome to CS 250!")
print("Python is hard!")
print("Python is useful")

Welcome to CS 250!
Python is hard!
Python is useful


## Part 3: Comments, Strings, and Output

⏱ **Target time: 8 minutes**


📘 **Read**

Three ideas you will use in every program from now on:

- **Comment** — anything on a line after a `#`. Python ignores it when the program runs.
  Comments exist to explain your thinking to a human reader, including you next week.
  A good comment says *why*, not just *what*.
- **String** — text surrounded by quotation marks, such as `"Course: CS 250"`. The quotation
  marks mark where the text starts and stops. They are not part of the text and are not printed.
- **`print()`** — displays whatever is inside its parentheses as output, then moves to a new line.

Single quotes (`'like this'`) also work, as long as you use the same kind at both ends.


### Exercise 3.1 — Add a useful comment

✏️ **Your Task**

Add a comment on the line **above** the `print()` statement, explaining what that line does.
Then run the cell. The output should not change — comments do not affect what a program does.


In [5]:
# Exercise 3.1
# TODO: Write your comment on the line below this one.
# just try my first comment
print("Welcome to my program!")


Welcome to my program!


### Exercise 3.2 — Complete the program

✏️ **Your Task**

Replace each `TODO` comment with a `print()` statement that displays the line described.
When you are done, the output should have three lines.


In [12]:
# Exercise 3.2
# This program displays information about CS 250

print("Course: CS 250")
print("Topic: Introduction to Programming")
print("Language: Python")


Course: CS 250
Topic: Introduction to Programming
Language: Python


### Exercise 3.3 — Formatting output

✏️ **Your Task**

Write a program that produces exactly this output:

```
************************
WELCOME TO CS 250
Programming starts here!
************************
```

Use one `print()` statement for each line — four in total. You only need `print()` and strings.


In [13]:
# Exercise 3.3
# TODO: Write four print statements that produce the output shown above.
# Hint: one print() statement per line of output.
print("************************")
print("WELCOME TO CS 250")
print("Programming starts here!")
print("************************")

************************
WELCOME TO CS 250
Programming starts here!
************************


## Part 4: Predict, Run, and Explain

⏱ **Target time: 7 minutes**

📘 **Read**

For each activity below: read the code, write your prediction **before** running it, then run
it and compare. Predicting first is what builds an accurate picture of what code does — being
wrong is useful, as long as you notice.


### Activity 4.1


In [14]:
# Activity 4.1
print("Line 1")
print("Line 2")


Line 1
Line 2


🤔 **Prediction** — what will this display? Write your answer before you run it.

*Type your answer here:*
Line 1
Line 2


Now run the cell above.

**Actual output** — write down what actually appeared:

*Type your answer here:*
Line 1
Line 2

**Explain it in one sentence** — why did it come out that way?

*Type your answer here:*
because it will show what inside of the print("")show


### Activity 4.2


In [15]:
# Activity 4.2
print(2 + 3)
print("2 + 3")


5
2 + 3


🤔 **Prediction** — will these two lines display the same thing? Write your answer before running.

*Type your answer here:*
error
2+3


Now run the cell above.

**Actual output:**

*Type your answer here:*
5
2+3
**Explain it in one sentence** — what is different about the two lines of code?

*Type your answer here:*
because 2+3=5, which is math calculation, print(5) directly, output is 5.
because it's a String mark, and will print out anything what inside the " " show.


### Activity 4.3


In [16]:
# Activity 4.3
# print("Hidden message")
print("Visible message")


Visible message


🤔 **Prediction** — which message or messages will appear, and why? Write your answer before running.

*Type your answer here:*
Visible message

Now run the cell above.

**Actual output:**

*Type your answer here:*
Visible message

**Explain it in one sentence:**

*Type your answer here:*
because it will exactly output what inside the " " show

## Part 5: Debugging Practice

⏱ **Target time: 10 minutes**


📘 **Read**

**Debugging** is finding and fixing problems in a program. Every programmer does it every day.
An error message is not a scolding — it is the most useful information on your screen.

Three kinds of problems, which differ by **when** they happen:

| Type | When it happens | What you see |
|---|---|---|
| **Syntax error** | Before anything runs | Python cannot understand the structure of your code, so the program never starts. |
| **Runtime error** | Partway through | The program starts, then hits something it cannot do and stops. |
| **Logic error** | Never announced | The program runs and finishes, but the result is not what you intended. |

**How to read an error message:** start at the **last line**. It names the type of error and
gives a short description. The lines above it show where Python was when the problem occurred.


### Exercise 5.1 — A syntax error

⚠️ **This cell will produce an error on purpose. That is expected — nothing is broken.**

🐞 **Debug**

1. Run the cell below and let it fail.
2. Read the **last line** of the error message.
3. Write your corrected version in the next cell.
4. Run your corrected cell.


In [17]:
# Exercise 5.1 - EXPECTED ERROR
# Running this cell produces an error on purpose.

print("Welcome to CS 250!)


SyntaxError: unterminated string literal (detected at line 4) (1757243281.py, line 4)

In [18]:
# Exercise 5.1 - your corrected version
# TODO: Rewrite the line below so that it runs without an error.
print("Welcome to CS 250!")


Welcome to CS 250!


✏️ **Your Task** — answer these three questions.

1. What type of error was this?
*Type your answer here:* Syntax error.
2. What did you change?
*Type your answer here:* I add " at the end of sentence after !, and before )
3. What happened after you reran the cell?
*Type your answer here:* it runs successful.


### Exercise 5.2 — A runtime error

⚠️ **This cell will also produce an error on purpose.**

🐞 **Debug**

1. Run the cell below and read the last line of the error message.
2. In the next cell, change the number you are dividing by so that the program runs successfully.

Dividing by zero has no answer in mathematics, so Python cannot complete it.


In [19]:
# Exercise 5.2 - EXPECTED ERROR
# Running this cell produces an error on purpose.

print(10 / 0)


ZeroDivisionError: division by zero

In [20]:
# Exercise 5.2 - your corrected version
# TODO: Change the number you are dividing by so this runs successfully.

print(10 / 1)


10.0


✏️ **Your Task** — answer these three questions.

1. What type of error was this?
*Type your answer here:* Runtime error.
2. What did you change?
*Type your answer here:* I change the denominator to 1，which cannot be zero.
3. What happened after you reran the cell?
*Type your answer here:* it runs successful, answer is 10.0


### Exercise 5.3 — A logic error

🐞 **Debug**

This cell runs without any error message — but the result does not match what the program says
it is doing.

1. Run the cell below.
2. Read the output and compare it with the message.
3. Write a corrected version in the next cell.


In [21]:
# Exercise 5.3
print("The result of 2 + 3 is:")
print(2 * 3)


The result of 2 + 3 is:
6


In [22]:
# Exercise 5.3 - your corrected version
# TODO: Fix the program so the result matches the message.
print("The result of 2 + 3 is:")
print(2 + 3)

The result of 2 + 3 is:
5


✏️ **Your Task** — answer these three questions.

1. What type of error was this?
*Type your answer here:* Logic error
2. What did you change?
*Type your answer here:* I change the 2nd print calculation 2 * 3 to 2 + 3
3. What happened after you reran the cell?
*Type your answer here:* it runs successful.


## Part 6: Mini Programming Challenge

⏱ **Target time: 10 minutes**

### Create a Digital Introduction Card

📘 **Read**

Write a program that introduces you, using only comments and `print()` statements.

Here is an example using a made-up student. Yours should show your own information and does
not need to look identical — match the shape, not the words.

```
================================
HELLO! I'M ALEX
Major: Business Analytics
Why programming? I want to automate repetitive tasks.
Technology I use: Google Maps
I'm ready to learn Python!
================================
```

**Your card must include:**

1. A decorative top border.
2. Your name.
3. Your academic program or major.
4. One reason you are interested in programming.
5. One technology you use regularly.
6. A closing message.
7. A decorative bottom border, matching the top one.

**Requirements:**

- At least one useful comment.
- At least six `print()` statements.
- Readable output.
- The top and bottom borders match.
- The cell runs without an error.
- The content is about you.

Use only comments and `print()`. You do not need variables, `input()`, loops, functions,
f-strings, or imports — none of those have been introduced yet.


✏️ **Your Task** — write your program in the cell below.


In [25]:
# Digital Introduction Card
# TODO: Add your print statements below.
# my basic information
print("===========")
print("Name: Yi Cui")
print("Major: Computer Science")
print("Why programming? I want to learn how python works.")
print("Technology I use: gemini ")
print("I'm ready to learn!")
print("===========")

Name: Yi Cui
Major: Computer Science
Why programming? I want to learn how python works.
Technology I use: gemini 
I'm ready to learn!


⭐ **Optional extension** — if you finish early

Add a second section to your card describing something you would like to create with Python.
Use only comments and `print()`, as before.


In [26]:
# Optional extension
# TODO: Add a second section to your card.
# learn how to programming
print("programming logic")

programming logic


## Part 7: Reflection and Submission

⏱ **Target time: 3 minutes**


💭 **Reflection**

Answer in a sentence or two each. Double-click this cell to edit it.

**1. What is the difference between a code cell and a Markdown cell?**

*Type your answer here:*
Code cells for write and run python code, and Markdown cells for explanations or comment text.

**2. What debugging step helped you most today?**

*Type your answer here:* know the syntax error, help me standard my coding.

**3. What is one thing you can now do in Python that you could not do before this lab?**

*Type your answer here:* I learned how to write basic python sentence.


✅ **Check Your Work** — final self-check

Edit this cell and put an `x` between the brackets for each item you have completed.

- [x ] Every required code cell has been completed.
- [x ] Every code cell has been run.
- [x ] The notebook contains no unintended error messages.
- [x ] The Digital Introduction Card meets all of its requirements.
- [x ] The reflection questions are answered.
- [x ] My name and student ID are filled in at the top.
- [x ] The notebook has been renamed correctly.

**Note:** the two cells in Part 5 marked *EXPECTED ERROR* are supposed to produce errors.
Those do not count as unintended errors — leave them as they are.


### Submission

1. **Rename the notebook** using this pattern:
   `L01_LastName_FirstName.ipynb`
   (In Colab: **File → Rename**, or click the name at the top left.)
2. **Run all completed cells** from top to bottom, so your output is visible.
3. **Save the notebook** (**File → Save**, or Ctrl/Cmd + S).
4. **Save on Github** (**File → Save a copy in Github**)
4. **Submit** the notebook GitHub URL to Canvas.
5. **Verify** that the file or link you submitted actually opens.

---

Well done — you have written, run, broken, fixed, and personalized a Python program.
Bring any question you still have to the next lecture or lab.
